# Generated by Django 5.1.4 on 2024-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumenes',
            name='cuerpo',
            field=models.CharField(max_length=500),
        ),
    ]
